language: node_js
node_js:
  - "stable"

services:
  - docker

cache:
  directories:
    - node_modules
script:
  - npm install

dist: trusty

deploy:
  provider: script
  script: bash ./docker_push.sh
  on:
    branch: master
