http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  stories:
    host: '*'
    paths: ['/stories/place/:placeId',
    '/stories/title/:keyword',
    '/stories/topStories/:numberOfStories',
    '/stories',
    '/stories/taxonomy',
    '/stories/taxonomy/solution/:solution',
    '/stories/taxonomy/strategy/:strategy',
    '/stories/taxonomy/sector/:sector',
    '/stories/getPreview',
    '/stories/sector/:sector',
    '/stories/solution/:solution',
    '/stories/strategy/:strategy']
  storiesVerified:
    host: '*'
    paths: ['/stories/story/comment',
    '/stories/delete/:storyId',
    '/stories/create',
    '/stories/:storyID/like/:userID', 
    '/stories/:storyID/unlike/:userID',
    '/stories/unrated',
    '/stories/description/:description',
    '/stories/:storyID/flag/:userID',
    '/stories/:storyID/unflag/:userID',
    '/stories/rating/update']
  places:
    host: '*'
    paths: ['/places/v1/:placeName', '/places/v1/:placeId/similar', '/places/v1/:placeId/similar/advanced','/places/v1/nearest']
  users:
    host: '*'
    paths: ['/user/login']
  usersVerified:
    host: '*'
    paths: ['/user/searchname',
    '/user/:userId',
    '/user/:userId/:roleId',
    '/user/blacklist/:userId',
    '/user/unblacklist/:userId',
    '/user/request_role_change/:userId/:roleChangeId', 
    '/user/get_all_role_update_requests']
  geoserver:
    host: '*'
    paths: ['/geoserver/wfs']
serviceEndpoints:
  storiesService:
    url: 'https://backend-mongo-stories.azurewebsites.net/v1'
  storiesVerifiedService:
    url: 'https://backend-mongo-stories.azurewebsites.net/v1'
  placesService:
    url: 'https://places-postgres2.azurewebsites.net/api'
  userService:
    url: 'https://usermicroservice-climatetree.azurewebsites.net/v1'
  userVerifiedService:
    url: 'https://usermicroservice-climatetree.azurewebsites.net/v1'
  geoserverService:
    url: 'https://climatetree-geoserver.azurewebsites.net'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
pipelines:
  - name: storiesVerified
    apiEndpoints:
      - storiesVerified
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD,PUT,PATCH,POST,DELETE'
      - jwt:
          - action:
              checkCredentialExistence: false
              secretOrPublicKey: ${ASD_KEY}
      - proxy:
          - action:
              serviceEndpoint: storiesVerifiedService 
              changeOrigin: true
      - log: # policy name
        - action:    # array of condition/actions objects
            message: ${req.method} ${req.originalUrl} 
  - name: stories
    apiEndpoints:
      - stories
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD,PUT,PATCH,POST,DELETE'
      - proxy:
          - action:
              serviceEndpoint: storiesService 
              changeOrigin: true
      - log: # policy name
        - action:    # array of condition/actions objects
            message: ${req.method} ${req.originalUrl}          
  - name: places
    apiEndpoints:
      - places
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD,PUT,PATCH,POST,DELETE'
      - proxy:
          - action:
              serviceEndpoint: placesService 
              changeOrigin: true
      - log: # policy name
          - action:    # array of condition/actions objects
              message: ${req.method} ${req.originalUrl} 
  - name: users
    apiEndpoints:
      - users
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD,PUT,PATCH,POST,DELETE'
      - proxy:
          - action:
              serviceEndpoint: userService 
              changeOrigin: true
      - log: # policy name
        - action:    # array of condition/actions objects
            message: ${req.method} ${req.originalUrl}
  - name: usersVerified
    apiEndpoints:
      - usersVerified
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD,PUT,PATCH,POST,DELETE'
      - jwt:
          - action:
              checkCredentialExistence: false
              secretOrPublicKey: ${ASD_KEY}        
      - proxy:
          - action:
              serviceEndpoint: userVerifiedService 
              changeOrigin: true
      - log: # policy name
        - action:    # array of condition/actions objects
            message: ${req.method} ${req.originalUrl}
  - name: geoserver
    apiEndpoints:
      - geoserver
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD,PUT,PATCH,POST,DELETE'
      - proxy:
          - action:
              serviceEndpoint: geoserverService 
              changeOrigin: true
      - log: # policy name
        - action:    # array of condition/actions objects
            message: ${req.method} ${req.originalUrl}
